name: horizontal_list_view
description: Simple horizontal list view widget for displaying a list of items in a horizontal layout with fixed crosAxisCount.
version: 1.0.4
homepage: https://github.com/Nika0000/flutter_horizontal_list_view
repository: https://github.com/Nika0000/flutter_horizontal_list_view

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: